name: Build ESurfingDialer with Gradle

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'zulu'
        
    - name: Build with Gradle
      run: |
        ls -lR
        ./gradlew shadowJar
      
    - name: Upload archive
      uses: actions/upload-artifact@v1
      with:
         name: ESurfingDialer-1.4.0-all.jar
         path: ./build/libs/ESurfingDialer-1.4.0-all.jar
